site_name: STEMAIDE Docs
site_description: Documentation for STEMAIDE, a platform for STEMAIDE Kit Manual.
site_url: https://docs.stemaide.com


theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/stemaide-logo-white-footer.128px.webp

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.share
    - content.code.copy
    - content.tooltips

extra_css:
  - stylesheets/extra.css

font:
    text: Inter
    code: JetBrains Mono


plugins:
  - search
  - tags

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  

  - Guides:
      - User Guide: guides/user-guide.md
      - Beginner's Use Case: 1.0/version1.md
      - Intermediate Use Case: 2.0/version2.md
      - Advanced Use Case: 3.0/version3.md
      - Developer Guide: guides/developer-guide.md 

  - Changelog: CHANGELOG.md
  - Contributing: CONTRIBUTING.md
  - About: about.md
  - Code of Conduct: code-of-conduct.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight:
      use_pygments: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/whatsapp
      link: https://www.whatsapp.com/channel/0029VaCyaNN5a23vbdCABI0n
      name: Chat with us on WhatsApp
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/stemaideafrica
      name: STEMAIDE on Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/stemaideafrica
      name: STEMAIDE on Instagram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/stemaideafrica
      name: STEMAIDE on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/stemaide-africa
      name: STEMAIDE on LinkedIn
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@stemaide?_t=ZM-8xaIGd6aIR6&_r=1
      name: STEMAIDE on TikTok

  generator: false 
  homepage: /
  
